FROM php:5.6-fpm

MAINTAINER Stephan <lishufan00@aliyun.com>

ADD ./fad.ini /usr/local/etc/php/conf.d
ADD ./fad.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# install mcrypt library
RUN docker-php-ext-install mcrypt

# configure gd library
RUN docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-freetype-dir=/usr/include/freetype2

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    gd \
    mysql \
    mbstring

# Install memcached
RUN pecl install memcached \
    && docker-php-ext-enable memcached

# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN echo 'xdebug.remote_autostart=true'                 >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo 'xdebug.remote_enable=on'                      >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo 'xdebug.remote_port=9000'                      >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo 'xdebug.remote_handler=dbgp'                   >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \ 
    echo 'xdebug.remote_connect_back=on'                >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo 'xdebug.profile_enable=0'                      >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    echo 'xdebug.profile_output_dir="/temp/profiledir"' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini;

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
