version: '2'

services:

### work space ###
    workspace:
        build: ./workspace
        volumes:
            - ./workspace/backup.sh:/backup.sh
            - ./workspace/restore.sh:/restore.sh
        volumes_from:
            - application
            - data
        links:
            - mysql
        env_file:
            - ~/fad.env

### PHP-FPM Container ###

    php-fpm:
        build:
             context: ./php-fpm
             dockerfile: Dockerfile-56
        volumes_from:
             - application
             - data
        expose:
             - "9000"

### Fad application ###

    application:
        build: ./application
        volumes:
            - ../:/var/www

### Nginx Server Container ###

    nginx:
        build: ./nginx
        volumes_from:
            - application
            - data
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container ###

    mysql:
        build: ./mysql
        volumes_from:
            - data
        ports:
            - "3306:3306"
        env_file:
            - ~/fad.env

### Data Container: database and application data. ###

    data:
        build: ./data
        volumes:
            - ../data-volume/db-backup/:/db-backup
            - ../data-volume/logs/nginx/:/var/log/nginx
            - ../data-volume/app-data/:/var/app-data
